const menuOptions = [
    {
      name: " X-Kids",
      id: 0,
      quantity: 0,
      price: 24.99,
      category: "dev",
      vegan: false,
      img: "./assets/dev-fury.jpg",
    },
    {
      name: "X-Burguer Junior",
      id: 1,
      quantity: 0,
      price: 27.99,
      category: "dev",
      vegan: false,
      img: "./assets/dev-junior.jpg",
    },
    {
      name: "X-Chicken",
      id: 2,
      quantity: 0,
      price: 29.99,
      category: "dev",
      vegan: false,
      img: "./assets/dev-chicken.jpg",
    },
    {
      name: "X-Bacon",
      id: 3,
      quantity: 0,
      price: 32.99,
      category: "dev",
      vegan: false,
      img: "./assets/dev-bacon.jpg",
    },
    {
      name: "X-Burguer Vegano",
      id: 4,
      quantity: 0,
      price: 34.99,
      category: "dev",
      vegan: true,
      img: "./assets/dev-vegano.jpg",
    },
    {
      name: "X-Salada Duplo",
      id: 5,
      quantity: 0,
      price: 37.99,
      category: "dev",
      vegan: false,
      img: "./assets/dev-pleno.jpg",
    },
    {
      name: "Cheddar Duplo",
      id: 6,
      quantity: 0,
      price: 39.99,
      category: "dev",
      vegan: false,
      img: "./assets/dev-cheddar.jpg",
    },
    {
      name: "X-Burguer Fit",
      id: 7,
      quantity: 0,
      price: 42.99,
      category: "dev",
      vegan: true,
      img: "./assets/dev-fit.jpg",
    },
    {
      name: "X-Salada Hot",
      id: 8,
      quantity: 0,
      price: 44.99,
      category: "dev",
      vegan: false,
      img: "./assets/dev-splash.jpg",
    },
    {
      name: "X-Monster",
      id: 9,
      quantity: 0,
      price: 47.99,
      category: "dev",
      vegan: false,
      img: "./assets/dev-senior.jpg",
    },
    
    {
      name: "Batata Frita Tradicional",
      id: 10,
      quantity: 0,
      price: 14.99,
      category: "frie",
      vegan: false,
      img: "./assets/frita-tradicional.jpg",
    },
    {
      name: "Batata Frita com Cheddar",
      id: 11,
      quantity: 0,
      price: 19.99,
      category: "frie",
      vegan: false,
      img: "./assets/frita-cheddar.png",
    },
    {
      name: "Batata Frita com Calabresa",
      id:12,
      quantity: 0,
      price: 24.99,
      category: "frie",
      vegan: false,
      img: "./assets/frita-calabresa.jpg",
    },
    {
      name: "Batata Frita com Nuggets",
      id: 13,
      quantity: 0,
      price: 29.99,
      category: "frie",
      vegan: false,
      img: "./assets/frita-nuggets.jpg",
    },
   
  ];